### ISSUE TITLE
PdfJumbler distributed on Flathub.org

### ISSUE THREAD

**Issue by nbenitez** [mgropp/pdfjumbler#6]
Hi Martin,

[Flathub](https://flathub.org) is a build and distribution platform for Linux apps, packaged in
a way that makes them portable and running on all major distributions.
Anyone can submit an app (we're not doing it for profit), but one of the
requirements is to reach out to the application's authors if they would
like to help with maintenance and thus making that distribution channel
considered official.

[I've just submitted PdfJumbler for review](https://github.com/flathub/flathub/pull/2074) to be published in https://flathub.org.
The usual maintenance for new releases is just changing version string and
the file checksum. The rest is done by flathub's build infraestructure. 

It's understandable if you can't commit to maintaining it, I can do the new
version updates as I'm the original packager and interested in having
PdfJumbler on flathub, but we'd like to know **if you are not against 
distributing it on Flathub in general**.

Thank you,
Nelson

**Comment by mgropp** [comment]
Hi Nelson!

Thanks for adding PdfJumbler on Flathub! I wasn't aware of it before, but sure, go ahead!
At this point I'd prefer to be responsible only for the releases here, but I'm definitely happy to support you if you want to publish them on Flathub.

Cheers!
Martin

**Comment by nbenitez** [comment]
Thank you, I'll let you know when it's finally published.

**Comment by nbenitez** [comment]
> Thank you, I'll let you know when it's finally published.

I forgot to let you know, flathub page is https://flathub.org/apps/com.github.mgropp.PdfJumbler

If you want to be admin in https://github.com/flathub/com.github.mgropp.PdfJumbler just let me know. 

Thanks
