### ISSUE TITLE
Kindly see this Java project if it is suitable to you to fork it or get usefulness for pdfjumbler

### ISSUE THREAD

**Issue by Nokia808** [mgropp/pdfjumbler#7]
Hi.

Kindly, see the following project which is unfortunately killed by it's author (no further development !!):
http://jpdftweak.sourceforge.net/
https://sourceforge.net/projects/jpdftweak/

Look to it's user manual to see how much it is powerful:
http://jpdftweak.sourceforge.net/manual/index.html

It has need to add only a further 5 or 6 new feature to be nearly complete suite for PDF !

I asked many developers to fork it, but since it is written in Java no one of them interested in it !

Instead of building completely new PDF tool from scratch, why not start from jpdftweak ??

jpdftweak has no build in viewer. But even so, user can use it in conjugation with Okular because last support "autoreload feature" - see:
https://gitlab.com/scarpetta/pdfmixtool/-/issues/43
Just add new feature of "save" to jpdftweak (which is one of 5 or 6 new features needed to be added to it), user can use it easily with Okular in same way like that with PDF Mix Tool ......

But the backends of jpdftweak are upgraded by their developers since long time - see:
1) itext:
https://itextpdf.com/en
https://github.com/itext/i7j-pdfsweep
2) jgoodies:
http://www.jgoodies.com/
http://www.jgoodies.com/freeware/libraries/forms/
I do not know how this will impact further development/fork of jpdftweak .......

If you are interested in forking jpdftweak then, kindly, inform me.

**Comment by mgropp** [comment]
Hi Nokia808!
Thanks for mentioning this. Right now, I just don't have the time for another project, so I'm afraid I won't be able to take over... :(
