### ISSUE TITLE
Feature request: Tile view for PDF Jumbler

### ISSUE THREAD

**Issue by Just-Another-Gnumer** [mgropp/pdfjumbler#8]
Hello, I am suggesting a feature enhancement for pdfFJumbler to include a tile view mode for PDF pages. This will show PDF pages side by side.

I would also like to mention that another PDF tool named "pdfarranger" recently (early 2020) broke the ability to save local PDF bookmarks. Meaning local hyperlinks break after saving. This forced me to build old versions of PDFarranger on my Linux distro to preserve my workflow. Your tool has all the features I need without any issues. I even think your tool is better then PDFarranger because of the Alt Arrow ability to move pages.

**Comment by mgropp** [comment]
Hi Gnumer!
Oh, thank you! 😊

-- Good thing it's a public holiday + Corona! If you want to check it out, there's a preliminary version on the master branch. :)

**Comment by mgropp** [comment]
Implemented in v0.4.0

**Comment by Just-Another-Gnumer** [comment]
Thank you, the tiling feature looks very nice. 

![image](https://user-images.githubusercontent.com/78667207/113482212-15161380-948d-11eb-9490-fb2c62ece76d.png)

I just wish the scroll (zoom in and out) was less jagged and more smooth.  Happy Easter
